version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: film_school_db
    environment:
      POSTGRES_DB: film_school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <insert password here>
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: film_school_app
    ports:
      - "8091:8091"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/film_school
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: <insert password here>
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
